import { upload } from '@vercel/blob/client';
import { readFile } from 'node:fs/promises';
const BASE = 'https://markpress-zeta.vercel.app';
const path = process.argv[2], name = process.argv[3];
const buf = await readFile(path);
const blob = await upload(name, new File([buf], name, {type:'text/markdown'}), { access:'public', handleUploadUrl:`${BASE}/api/upload` });
const t1 = Date.now();
const res = await fetch(`${BASE}/api/convert`, { method:'POST', headers:{'content-type':'application/json'}, body: JSON.stringify({ blobUrl: blob.url, filename: name, size: buf.length }) });
const txt = await res.text();
console.log('HTTP', res.status, 'in', ((Date.now()-t1)/1000).toFixed(1)+'s');
console.log('x-vercel-error:', res.headers.get('x-vercel-error'));
console.log('body:', txt.slice(0,200));
